import { MigrationInterface, QueryRunner } from "typeorm";

export class ModelsCreated1676040888706 implements MigrationInterface {
    name = 'ModelsCreated1676040888706';

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "communities" ("id" SERIAL NOT NULL, "_id" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "name" character varying NOT NULL, "title" character varying NOT NULL, "description" text, "imageUrn" character varying, "bannerUrn" character varying, "communityType" character varying NOT NULL DEFAULT 'PUBLIC', "userId" uuid NOT NULL, "username" character varying NOT NULL, CONSTRAINT "UQ_9f2d3e798db2c30f252f7d6b116" UNIQUE ("_id"), CONSTRAINT "UQ_501bb6c8f7c8e8a7d614d9435f6" UNIQUE ("name"), CONSTRAINT "PK_fea1fe83c86ccde9d0a089e7ea2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_9f2d3e798db2c30f252f7d6b11" ON "communities" ("_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_501bb6c8f7c8e8a7d614d9435f" ON "communities" ("name") `);
        await queryRunner.query(`CREATE TYPE "public"."votes_votetype_enum" AS ENUM('UPVOTE', 'DOWNVOTE')`);
        await queryRunner.query(`CREATE TABLE "votes" ("id" SERIAL NOT NULL, "_id" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "voteType" "public"."votes_votetype_enum" NOT NULL DEFAULT 'UPVOTE', "userId" uuid NOT NULL, "postId" integer, "commentId" integer, CONSTRAINT "UQ_35890aaea4f6f03c436eba8dd53" UNIQUE ("_id"), CONSTRAINT "PK_f3d9fd4a0af865152c3f59db8ff" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_35890aaea4f6f03c436eba8dd5" ON "votes" ("_id") `);
        await queryRunner.query(`CREATE TABLE "comments" ("id" SERIAL NOT NULL, "_id" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "identifier" character varying NOT NULL, "body" character varying NOT NULL, "userId" uuid NOT NULL, "postId" integer NOT NULL, CONSTRAINT "UQ_09028bba28e1e189969ab502fea" UNIQUE ("_id"), CONSTRAINT "PK_8bf68bc960f2b69e818bdb90dcb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_09028bba28e1e189969ab502fe" ON "comments" ("_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_8e7297165a3d53fa13b720bb11" ON "comments" ("identifier") `);
        await queryRunner.query(`CREATE TABLE "posts" ("id" SERIAL NOT NULL, "_id" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "identifier" character varying NOT NULL, "title" character varying NOT NULL, "slug" character varying NOT NULL, "body" text, "imageUrn" character varying, "userId" uuid NOT NULL, "communityId" uuid NOT NULL, "voteCount" integer NOT NULL DEFAULT '0', "commentCount" integer NOT NULL DEFAULT '0', CONSTRAINT "UQ_399179b79c5b2030e8c0022bf48" UNIQUE ("_id"), CONSTRAINT "PK_2829ac61eff60fcec60d7274b9e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_399179b79c5b2030e8c0022bf4" ON "posts" ("_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_152316363d20c399f934c4f74b" ON "posts" ("identifier") `);
        await queryRunner.query(`CREATE INDEX "IDX_54ddf9075260407dcfdd724857" ON "posts" ("slug") `);
        await queryRunner.query(`CREATE TYPE "public"."users_authtype_enum" AS ENUM('EMAIL_AND_PASSWORD', 'GOOGLE')`);
        await queryRunner.query(`CREATE TABLE "users" ("id" SERIAL NOT NULL, "_id" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "email" character varying NOT NULL, "username" character varying NOT NULL, "password" character varying, "authType" "public"."users_authtype_enum" NOT NULL DEFAULT 'EMAIL_AND_PASSWORD', "profilePicUrn" character varying, "karma" character varying NOT NULL DEFAULT '0', "isActive" boolean NOT NULL DEFAULT false, "isVerified" boolean NOT NULL DEFAULT false, CONSTRAINT "UQ_46c438e5a956fb9c3e86e73e321" UNIQUE ("_id"), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "UQ_fe0bb3f6520ee0469504521e710" UNIQUE ("username"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_46c438e5a956fb9c3e86e73e32" ON "users" ("_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_97672ac88f789774dd47f7c8be" ON "users" ("email") `);
        await queryRunner.query(`CREATE INDEX "IDX_fe0bb3f6520ee0469504521e71" ON "users" ("username") `);
        await queryRunner.query(`CREATE TABLE "members" ("id" SERIAL NOT NULL, "memberType" character varying NOT NULL DEFAULT 'MEMBER', "userId" uuid NOT NULL, "communityId" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_5184acae437bf26968dabfa4e12" PRIMARY KEY ("id", "userId", "communityId"))`);
        await queryRunner.query(`ALTER TABLE "communities" DROP COLUMN "communityType"`);
        await queryRunner.query(`ALTER TABLE "communities" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "members" DROP CONSTRAINT "PK_5184acae437bf26968dabfa4e12"`);
        await queryRunner.query(`ALTER TABLE "members" ADD CONSTRAINT "PK_59e47e837a178dec6ddd4d385b5" PRIMARY KEY ("userId", "communityId")`);
        await queryRunner.query(`ALTER TABLE "members" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "members" DROP COLUMN "memberType"`);
        await queryRunner.query(`ALTER TABLE "members" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "members" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "communities" ADD "communityType" character varying NOT NULL DEFAULT 'PUBLIC'`);
        await queryRunner.query(`ALTER TABLE "communities" ADD "userId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "members" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "members" DROP CONSTRAINT "PK_59e47e837a178dec6ddd4d385b5"`);
        await queryRunner.query(`ALTER TABLE "members" ADD CONSTRAINT "PK_5184acae437bf26968dabfa4e12" PRIMARY KEY ("userId", "communityId", "id")`);
        await queryRunner.query(`ALTER TABLE "members" ADD "memberType" character varying NOT NULL DEFAULT 'MEMBER'`);
        await queryRunner.query(`ALTER TABLE "members" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "members" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "members" DROP CONSTRAINT "PK_5184acae437bf26968dabfa4e12"`);
        await queryRunner.query(`ALTER TABLE "members" ADD CONSTRAINT "PK_59e47e837a178dec6ddd4d385b5" PRIMARY KEY ("userId", "communityId")`);
        await queryRunner.query(`CREATE INDEX "IDX_839756572a2c38eb5a3b563126" ON "members" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_3823a309cefe8b838dcc22aa27" ON "members" ("communityId") `);
        await queryRunner.query(`ALTER TABLE "communities" ADD CONSTRAINT "FK_250d3303fef1c1f9bc4804b24ac" FOREIGN KEY ("userId") REFERENCES "users"("_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "votes" ADD CONSTRAINT "FK_5169384e31d0989699a318f3ca4" FOREIGN KEY ("userId") REFERENCES "users"("_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "votes" ADD CONSTRAINT "FK_b5b05adc89dda0614276a13a599" FOREIGN KEY ("postId") REFERENCES "posts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "votes" ADD CONSTRAINT "FK_554879cbc33538bf15d6991f400" FOREIGN KEY ("commentId") REFERENCES "comments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comments" ADD CONSTRAINT "FK_7e8d7c49f218ebb14314fdb3749" FOREIGN KEY ("userId") REFERENCES "users"("_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comments" ADD CONSTRAINT "FK_e44ddaaa6d058cb4092f83ad61f" FOREIGN KEY ("postId") REFERENCES "posts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "posts" ADD CONSTRAINT "FK_ae05faaa55c866130abef6e1fee" FOREIGN KEY ("userId") REFERENCES "users"("_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "posts" ADD CONSTRAINT "FK_e5f99a0b3edb7e1867f44b2cf4c" FOREIGN KEY ("communityId") REFERENCES "communities"("_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "communities" ADD CONSTRAINT "FK_6b1e067767d11fdfa0d5d3edea4" FOREIGN KEY ("username") REFERENCES "users"("username") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "members" ADD CONSTRAINT "FK_839756572a2c38eb5a3b563126e" FOREIGN KEY ("userId") REFERENCES "users"("_id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "members" ADD CONSTRAINT "FK_3823a309cefe8b838dcc22aa27a" FOREIGN KEY ("communityId") REFERENCES "communities"("_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "members" DROP CONSTRAINT "FK_3823a309cefe8b838dcc22aa27a"`);
        await queryRunner.query(`ALTER TABLE "members" DROP CONSTRAINT "FK_839756572a2c38eb5a3b563126e"`);
        await queryRunner.query(`ALTER TABLE "communities" DROP CONSTRAINT "FK_6b1e067767d11fdfa0d5d3edea4"`);
        await queryRunner.query(`ALTER TABLE "posts" DROP CONSTRAINT "FK_e5f99a0b3edb7e1867f44b2cf4c"`);
        await queryRunner.query(`ALTER TABLE "posts" DROP CONSTRAINT "FK_ae05faaa55c866130abef6e1fee"`);
        await queryRunner.query(`ALTER TABLE "comments" DROP CONSTRAINT "FK_e44ddaaa6d058cb4092f83ad61f"`);
        await queryRunner.query(`ALTER TABLE "comments" DROP CONSTRAINT "FK_7e8d7c49f218ebb14314fdb3749"`);
        await queryRunner.query(`ALTER TABLE "votes" DROP CONSTRAINT "FK_554879cbc33538bf15d6991f400"`);
        await queryRunner.query(`ALTER TABLE "votes" DROP CONSTRAINT "FK_b5b05adc89dda0614276a13a599"`);
        await queryRunner.query(`ALTER TABLE "votes" DROP CONSTRAINT "FK_5169384e31d0989699a318f3ca4"`);
        await queryRunner.query(`ALTER TABLE "communities" DROP CONSTRAINT "FK_250d3303fef1c1f9bc4804b24ac"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3823a309cefe8b838dcc22aa27"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_839756572a2c38eb5a3b563126"`);
        await queryRunner.query(`ALTER TABLE "members" DROP CONSTRAINT "PK_59e47e837a178dec6ddd4d385b5"`);
        await queryRunner.query(`ALTER TABLE "members" ADD CONSTRAINT "PK_5184acae437bf26968dabfa4e12" PRIMARY KEY ("userId", "communityId", "id")`);
        await queryRunner.query(`ALTER TABLE "members" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "members" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "members" DROP COLUMN "memberType"`);
        await queryRunner.query(`ALTER TABLE "members" DROP CONSTRAINT "PK_5184acae437bf26968dabfa4e12"`);
        await queryRunner.query(`ALTER TABLE "members" ADD CONSTRAINT "PK_59e47e837a178dec6ddd4d385b5" PRIMARY KEY ("userId", "communityId")`);
        await queryRunner.query(`ALTER TABLE "members" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "communities" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "communities" DROP COLUMN "communityType"`);
        await queryRunner.query(`ALTER TABLE "members" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "members" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "members" ADD "memberType" character varying NOT NULL DEFAULT 'MEMBER'`);
        await queryRunner.query(`ALTER TABLE "members" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "members" DROP CONSTRAINT "PK_59e47e837a178dec6ddd4d385b5"`);
        await queryRunner.query(`ALTER TABLE "members" ADD CONSTRAINT "PK_5184acae437bf26968dabfa4e12" PRIMARY KEY ("id", "userId", "communityId")`);
        await queryRunner.query(`ALTER TABLE "communities" ADD "userId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "communities" ADD "communityType" character varying NOT NULL DEFAULT 'PUBLIC'`);
        await queryRunner.query(`DROP TABLE "members"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fe0bb3f6520ee0469504521e71"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_97672ac88f789774dd47f7c8be"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_46c438e5a956fb9c3e86e73e32"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."users_authtype_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_54ddf9075260407dcfdd724857"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_152316363d20c399f934c4f74b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_399179b79c5b2030e8c0022bf4"`);
        await queryRunner.query(`DROP TABLE "posts"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8e7297165a3d53fa13b720bb11"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_09028bba28e1e189969ab502fe"`);
        await queryRunner.query(`DROP TABLE "comments"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_35890aaea4f6f03c436eba8dd5"`);
        await queryRunner.query(`DROP TABLE "votes"`);
        await queryRunner.query(`DROP TYPE "public"."votes_votetype_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_501bb6c8f7c8e8a7d614d9435f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9f2d3e798db2c30f252f7d6b11"`);
        await queryRunner.query(`DROP TABLE "communities"`);
    }
}
